cc_library(
    name = "reg_service",
    srcs = ["registeration.cpp"],
    hdrs = ["registeration.h"],
    visibility = [
        "//main:__pkg__",
        "//services/test:__pkg__",
    ],
    deps = [
        "//libraries:cred_lib",
    ],
)
