cc_library(
    name = "cred_lib",
    srcs = ["user.cpp"],
    hdrs = ["user.h"],
    visibility = [
        "//libraries/test:__pkg__",
        "//main:__pkg__",
        "//services:__pkg__",
    ],
)
